version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: x64
clone_script:
  - git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%
  - git checkout -qf %APPVEYOR_REPO_COMMIT%
install:
  - git submodule update --init --recursive
before_build:
  - nuget restore
build:
  project: FFXIVMonReborn.sln
  parallel: true
  verbosity: normal
artifacts:
  - path: bin